apiVersion: v1
kind: Service
metadata:
  name: class-db
spec:
  selector:
    app: class-db
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP   # only reachable inside the cluster