# Defines the Submission and FileRef ORM models for the submission service.
# Binary file data is stored in MinIO — only metadata is stored in the database.

from uuid import uuid4
from sqlalchemy import UUID, Column, String, DateTime, Integer, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class Submission(Base):
    __tablename__ = "submissions"

    # UUID primary key — generated by Python at insert time.
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)

    # Foreign references to assignment and student — plain UUIDs,
    # no FK constraints since those records live in other services.
    assignment_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    student_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # studentName is denormalized here to avoid calling the user service
    # on every read. Acceptable tradeoff for a course project.
    student_name = Column(String, nullable=False)

    submitted_at = Column(DateTime, server_default=func.now())

    # Submission lifecycle: submitted | graded | returned
    status = Column(String, nullable=False, default="submitted")

    # One submission can have multiple files
    files = relationship("FileRef", back_populates="submission",
                                 cascade="all, delete-orphan")


class FileRef(Base):
    __tablename__ = "file_refs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)

    # Foreign key to the parent submission — this is an internal FK
    # within the same database so a real constraint is appropriate here.
    submission_id = Column(UUID(as_uuid=True),
                           ForeignKey("submissions.id"), nullable=False)

    name = Column(String, nullable=False)   # original filename
    size_bytes = Column(Integer, nullable=False)
    content_type = Column(String, nullable=False)

    # Path used to retrieve the file from MinIO e.g. "submissions/uuid/filename"
    storage_key  = Column(String, nullable=False)

    submission = relationship("Submission", back_populates="files")