# Defines the User ORM model, which maps to the users table
# in the PostgreSQL database owned by this service.

from sqlalchemy import Column, String, DateTime
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from uuid import uuid4
from app.database import Base

class User(Base):
    __tablename__ = "users"

    # UUID primary key — generated by Python at insert time.
    # UUIDs are used instead of integer IDs to avoid collisions
    id         = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)

    name       = Column(String, nullable=False)

    # Email is unique and indexed — used as the primary identifier
    # for looking up users and preventing duplicate registrations.
    email      = Column(String, nullable=False, unique=True, index=True)

    # Role determines what the user can access in the application.
    # Valid values: "student" | "professor"
    # Enforced at the schema level via the Role literal type in schemas.py.
    role       = Column(String, nullable=False)

    created_at = Column(DateTime, server_default=func.now())