# Defines the Assignment ORM model, which maps to the assignments table
# in the PostgreSQL database owned by this service.

from uuid import uuid4
from sqlalchemy import UUID, Boolean, Column, Float, String, DateTime
from sqlalchemy.sql import func
from app.database import Base

class Assignment(Base):
    __tablename__ = "assignments"

    # UUID primary key — generated by Python at insert time.
    # UUIDs are used instead of integer IDs to avoid collisions.
    id                 = Column(UUID(as_uuid=True), primary_key=True, index=True, default=uuid4)

    # Foreign reference to the class this assignment belongs to.
    # Stored as a plain UUID with no FK constraint — the class service
    # owns that data and is queried via API, not a direct DB join.
    class_id           = Column(UUID(as_uuid=True), nullable=False)

    title              = Column(String, nullable=False)
    description        = Column(String, nullable=False, default="")
    due_at             = Column(DateTime, nullable=True)
    points_possible    = Column(Float, nullable=False, default=100.0)

    # Assignment lifecycle state: draft | open | closed
    status             = Column(String, nullable=False, default="open")

    allow_resubmission = Column(Boolean, nullable=False, default=True)
    created_at         = Column(DateTime, server_default=func.now())