# Defines the Class ORM model, which maps to the classes table
# in the PostgreSQL database owned by this service.

from uuid import uuid4
from sqlalchemy import UUID, Column, Integer, String, DateTime
from sqlalchemy.sql import func
from app.database import Base


class Class(Base):
    __tablename__ = "classes"

    # UUID primary key — generated by Python at insert time.
    # UUIDs are used instead of integer IDs to avoid collisions
    id             = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)

    # Course code displayed in the UI, e.g. "CSC258".
    code           = Column(String, nullable=False)
    name           = Column(String, nullable=False)
    description    = Column(String)

    # Foreign reference to the professor who owns this class.
    # Stored as a plain UUID with no FK constraint — the user service
    # owns that data and is queried via API, not a direct DB join.
    professor_id   = Column(UUID(as_uuid=True), nullable=False)
    professor_name = Column(String, nullable=False)

    # Term is stored as flat columns rather than a nested object
    # because relational databases don't have a native object type.
    # The ClassResponse schema reassembles these into a ClassTerm object
    # when returning responses to the frontend.
    term_season    = Column(String, nullable=False)   # spring|fall|winter|summer
    term_year      = Column(Integer, nullable=False)
    term_starts_on = Column(String, nullable=False)   # ISO date string
    term_ends_on   = Column(String, nullable=False)

    created_at     = Column(DateTime, server_default=func.now())