# Defines the Grade ORM model, which maps to the grades table
# in the PostgreSQL database owned by this service.

from uuid import uuid4
from sqlalchemy import UUID, Column, Float, String, DateTime
from sqlalchemy.sql import func
from app.database import Base

class Grade(Base):
    __tablename__ = "grades"

    # UUID primary key — generated by Python at insert time.
    # UUIDs are used instead of integer IDs to avoid collisions
    id              = Column(UUID(as_uuid=True), primary_key=True, index=True, default=uuid4)

    # Foreign reference to the submission being graded.
    # Stored as a plain UUID with no FK constraint — the submission service
    # owns that data and is queried via API, not a direct DB join.
    submission_id   = Column(UUID(as_uuid=True), nullable=False)

    # The score awarded and the maximum possible score for the assignment.
    # Both are stored here so grades can be displayed without needing to
    # call the assignment service on every read.
    score           = Column(Float, nullable=False)
    points_possible = Column(Float, nullable=False)

    # Optional written feedback from the professor, visible to the student.
    feedback        = Column(String, nullable=True)

    # Foreign reference to the professor who submitted this grade.
    # Stored as a plain UUID — resolved to a name via the user service if needed.
    graded_by_id    = Column(UUID(as_uuid=True), nullable=False)

    graded_at       = Column(DateTime, server_default=func.now())